################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  node-red:
    image: nodered/node-red:2.1.3
    restart: always
    container_name: nodered
    environment:
      - TZ=Europe/Rome
      - NODE_RED_ENABLE_PROJECTS=true
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data
  mongodb:
    image: mongo:4.4
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - node-red-net
    volumes:
      - mongodb-data:/data/db
  portainer:
    image: portainer/portainer-ce:2.9.3
    restart: always
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    networks:
      - node-red-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

volumes:
  node-red-data:
  mongodb-data:
  portainer-data:


networks:
  node-red-net:
